config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :fan_groups, only: [:show, :index] do
    resources :bookings, only: [:new, :create, :show]
  end
  resources :bookings, only: [:destroy]

  resources :users, only: [:show] do
    resources :bookings, only: [:index, :show, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :fan_group
  validates :date, presence: true
  validates :time, presence: true
  validates :location, presence: true
end

app/models/fan_group.rb
class FanGroup < ApplicationRecord
  has_many :bookings

  mount_uploader :photo, PhotoUploader

  validates :group_name, uniqueness: true, presence: true
  validates :category, presence: true
  validates :price, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @fan_group = FanGroup.find(params[:fan_group_id])
    @booking = Booking.new(booking_params)
    @booking.fan_group = @fan_group
    @booking.user = current_user
    if @booking.save
      redirect_to user_booking_path(current_user, @booking)
    else
      render 'fan_groups/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user, @booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time, :location)
  end

end

app/controllers/fan_groups_controller.rb
class FanGroupsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]


  # def index
  #   @fan_groups = FanGroup.all
  #   unless params[:city].blank?
  #     @fan_groups = FanGroup.where(city: params[:city].capitalize)
  #   end
  # end

  # def index
  #   @fan_groups = FanGroup.all
  #   unless params[:city].blank?
  #     sql_query = "city ILIKE :city AND category ILIKE :category AND price <= :price AND size <= :size "
  #     @fan_groups = FanGroup.where(sql_query, city: params[:city].capitalize, category: params[:category], price: params[:price], size: params[:size])
  #   end
  # end

    def index
      if params[:city].blank? && params[:category].blank? && params[:price].blank? && params[:size].blank?
          @fan_groups = FanGroup.all
      elsif params[:city].present? && params[:category].blank? && params[:price].blank? && params[:size].blank?
        @fan_groups = FanGroup.where("city ILIKE :city", city: params[:city])

      elsif params[:city].present? && params[:category].present? && params[:price].blank? && params[:size].blank?
        @fan_groups = FanGroup.where("category ILIKE :category AND city ILIKE :city ", category: params[:category], city: params[:city])

      elsif params[:city].present? && params[:category].present? && params[:price].present? && params[:size].blank?
        @fan_groups = FanGroup.where("price <= :price AND category ILIKE :category AND city ILIKE :city ", price: params[:price], category: params[:category], city: params[:city])

      elsif params[:city].present? && params[:category].present? && params[:price].present? && params[:size].present?
        @fan_groups = FanGroup.where("price <= :price AND category ILIKE :category AND city ILIKE :city AND size <= :size", price: params[:price], category: params[:category], city: params[:city], size: params[:size])

      elsif params[:city].present? && params[:category].blank? && params[:price].blank? && params[:size].present?
        @fan_groups = FanGroup.where("city ILIKE :city AND size <= :size", city: params[:city], size: params[:size])

      elsif params[:city].blank? && params[:category].blank? && params[:price].present? && params[:size].blank?
        @fan_groups = FanGroup.where("price <= :price", price: params[:price])

      else params[:city].present? && params[:category].blank? && params[:price].present? && params[:size].blank?
        @fan_groups = FanGroup.where("price <= :price AND city ILIKE :city", price: params[:price], city: params[:city])

      end





      # @fan_groups = @fan_groups.where("city ILIKE :city", city: params[:city]) if params[:city] != ''
      # @fan_groups = @fan_groups.where("price <= :price", price: params[:price]) if params[:price] != (nil || '')
      # @fan_groups = @fan_groups.where("category ILIKE :category", category: params[:category]) if params[:category] != nil
      # @fan_groups = @fan_groups.where("size <= :size", size: params[:size]) if params[:size] != nil
end


  #   unless params[:city].blank?
  #     sql_query = "city ILIKE :city AND category ILIKE :category AND price <= :price AND size <= :size "
  #     @fan_groups = FanGroup.where(sql_query, city: params[:city].capitalize, category: params[:category], price: params[:price], size: params[:size])
  #   end
  # end



    # raise
    # perform search code goes here
  #   render ‘index’
  # end

  # def index
  #   if params[:query].present?
  #     sql_query = "title ILIKE :query OR syllabus ILIKE :query"
  #     @movies = Movie.where(sql_query, query: "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end


def show
  @fan_group = FanGroup.find(params[:id])
  @booking = Booking.new
end

#params for image upload
def fan_group_params
  params.require(:fan_group).permit(:photo)
end

private

def params_fan_group
  params.require(:fan_groups).permit(:city, :group_name, :category, :price, :size, :description, :photo)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="booking-container">


<h2>These are all your bookings:</h2>

<% current_user.bookings.each do |booking| %>
    <li>city: <%= link_to booking.location, user_booking_path(current_user, booking) %></li>
    <li>date: <%= link_to booking.date, user_booking_path(current_user, booking) %></li>
    <li>at: <%= link_to booking.time, user_booking_path(current_user, booking) %></li>
    <%= link_to booking_path(booking), method: :delete do %>
        <i class="fas fa-trash-alt"></i>
    <% end %>

<% end %>
<br>

<%= link_to "Search for another group", fan_groups_path, class: "btn btn-primary" %>


<br>

</div>

app/views/bookings/show.html.erb
<div class="booking-container">
<h2>WOOHOO!</h2>
<h2>Your booking is <strong>Now Confirmed!</strong></h2>

<h4>Here are the details of your booking:</h4>
<h4> Location: <%= @booking.location %> </h4>
<h4> Time: <%= @booking.time %> </h4>
<h4> Date: <%= @booking.date %> </h4>

<%= link_to "See all my bookings", user_bookings_path %>
</div>

app/views/fan_groups/index.html.erb
<!-- put the form for search criteria here -->

<div class="container" >

  <form class="grouped_dropdown" action="/fan_groups" method="get">

    <div class="form-group">
      <label for="exampleSelectCity">City</label>
      <input value="<%= params[:city] %>"class="form-control" type="text" name="city" id="city" class="form-group">
    </div>

    <div class="form-group">
      <label for="exampleSelectPrice">Price</label>
      <input class="form-control" type="text" name="price" id="price"  class="form-group" value="">
<!--       <select class="form-control" id="exampleSelectPrice" required>
        <option value="">Select Price Range</option>
        <option value="50"> €0 to €50</option>
        <option value="100"> €51 to €100</option>
        <option value="150"> €101 to €150</option>
        <option value="200"> €151 to €200</option>
      </select> -->
    </div>

    <div class="form-group">
      <label for="exampleSelectCategory">Category</label>
      <select class="form-control" id="exampleSelectCategory"  name="category">
        <option value="">Select Category</option>
        <option value="Concert Hippies">Concert Hippies</option>
        <option value="Stand-up Comedy">Stand-up Comedy</option>
        <option value="Political Rally">Political Rally</option>
        <option value="Sport Fans">Sport Fans</option>
      </select>
    </div>

    <div class="form-group">
      <label for="exampleSelectGroupSize">Group Size</label>
      <select class="form-control" id="exampleSelectGroupSize" name="size">
        <option value="">Select Group Size</option>
        <option value="10">up to 10 peeps</option>
        <option value="30">up to 30 peeps</option>
        <option value="+30">this is getting ridiculous (+30)</option>
      </select>
    </div>

    <div>
      <button type="submit" class="adjusted btn btn-primary">Never Walk Alone</button>
    </div>

  </form>

</div>


<!-- container and cards banner here -->


<div class="container">
  <div class="cards">

    <% @fan_groups.each do |fan_group|  %>
    <div class="card-trip">

 <!--      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg">
  -->     <%= cl_image_tag(fan_group.photo)%>
      <div class="card-trip-infos">
        <div>
          <h2><%= link_to fan_group.group_name, fan_group_path(fan_group) %> </h2>
          <p> <%= fan_group.description %></p>
        </div>
        <h2 class="card-trip-pricing"> <p> € </p> <%= fan_group.price %>  </h2>
      </div>
    </div>
    <% end %>

  </div>
</div>




<!--
<div class="cards">

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>

</div>
 -->

<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <form action="">
        <#!-- Your form content
      </form>
    </div>
  </div>
</div>
 #-->

<!-- questions:
how to put in specific picture for cards,  -->


<%#= link_to fan_group.group_name, fan_group_path(fan_group)  %>

<!-- <div class="form-group">
      <label for="exampleSelectCategory">Category</label>
      <select class="form-control" id="exampleSelectCategory" required>
        <option value="">Select your Category</option>
        <option value="CH">Concert Hippies</option>
        <option value="SC">Stand-up Comedy</option>
        <option value="PR">Political Rally</option>
        <option value="SF">Sport Fans</option>
      </select>
    </div> -->

app/views/fan_groups/show.html.erb
<div class="profile">

  <div class="profile-description">
    <h3> <strong> <%= @fan_group.group_name %> </strong> </h3>

    <p> Category: <%= @fan_group.category %> </p>

    <p> Price: <%= @fan_group.price %>€ per booking</p>

    <p> Size of the group: <%= @fan_group.size %> </h4>

    <p> "<i><%= @fan_group.description %>" </i> <p>
    <p> <strong> Create a new booking: </strong> </p>



          <div class="form">
          <%= simple_form_for([@fan_group, @booking]) do |f| %>
          <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :time, as: :string, required: false, input_html: {class: "datepicker-nocalendar"} %>
          <%= f.input :location, input_html: {id: "booking_address"}  %>
          <%= f.submit "Submit a booking", class: "btn btn-primary" %>
          <% end %>


        </div>
    </div>

    <div class="profile-picture">
        <%= cl_image_tag(@fan_group.photo)%>
    </div>
</div>

  </div>



<%= javascript_pack_tag "autocomplete_pack" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_tag("fan_groups", method: :get, class: "search-engine") do %>

  <%= text_field_tag :city,
    params[:city],
    class: "form-control", id: "booking_address",
    placeholder: "Where are you?"
  %>


  <%= submit_tag(value = "Find A Fan Group")
   %>
<% end %>

<%= javascript_pack_tag "autocomplete_pack" %>

app/views/pages/home.html.erb
<div class="banner">

  <div id="search-field">
    <%= render 'form' %>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Fan-Logo.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", "/", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Help", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
    <div id="button"> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>